Feature/10: Base Api
frontend-team-12/ya-practicum-game pull request #30
Opened 2022-04-09 21:22 UTC by vishenkov

- Используем Axios
- Базовый класс для API + типы
- Фиксы сборки

2022-04-09 21:30 UTC, vishenkov commented on .babelrc
> +  "plugins": ["@babel/plugin-transform-runtime"]
плагин для поддержки async/await

2022-04-09 21:30 UTC, vishenkov commented on src/api/types.ts
> +export type User = {
Добавил сразу все типы из своего старого проекта

2022-04-09 21:30 UTC, vishenkov commented on webpack.config.ts
> +  devtool: 'inline-source-map',
сорус мапы для отладки в браузере

2022-04-10 00:14 UTC, Handaz requested changes

2022-04-10 00:14 UTC, Handaz commented on webpack.config.ts
> +  devtool: 'inline-source-map',
расскажешь поподробнее?

2022-04-10 00:14 UTC, Handaz commented on src/api/types.ts
> +export type User = {
В названиях типов добавь T (TUser, TLogin, и тд)

2022-04-10 00:15 UTC, Handaz requested changes

2022-04-10 00:15 UTC, Handaz commented on src/api/BaseApi.ts
> +  constructor(endpoint: string) {
С эндпоинтом круто сделал

2022-04-10 00:17 UTC, Handaz reviewed
Все очень хорошо, оставил только комментарий про нейминг типов и еще надо структуру папок поддерживать:
api --> AuthApi (папка) -> AuthApi.ts, index.ts и тд для других

2022-04-10 00:18 UTC, Handaz commented on src/api/BaseApi.ts
> +  constructor(endpoint: string) {
С эндпоинтом круто сделал)

2022-04-10 07:52 UTC, vishenkov commented on webpack.config.ts
> +  devtool: 'inline-source-map',
при отладке можно будет смотреть удобно прямо в бразуере
<img width="385" alt="Screenshot 2022-04-10 at 10 50 01" src="https://user-images.githubusercontent.com/11181413/162608314-bf43de5e-d79b-4e87-ab6d-2134de416f7e.png">

2022-04-10 09:10 UTC, Evgood approved these changes

2022-04-10 09:10 UTC, Evgood commented on src/api/BaseApi.ts
> +  _http: Axios;
а `_` это означает приватное поле? Может укажем `private` тогда. Где ранее в задачах обсуждали этот момент, что лучше всегда указывать `public` или `private` у методов

2022-04-10 09:48 UTC, vishenkov commented
> еще надо структуру папок поддерживать:
api --> AuthApi (папка) -> AuthApi.ts, index.ts и тд для других

здесь кмк нет смысла так делать - скорее всего, будет один файл для большинства api. А если и понадобятся дополнительные файлы, тогда и расширить с реэкспортом

2022-04-10 09:51 UTC, vishenkov commented on src/api/BaseApi.ts
> +  _http: Axios;
тут скорее `protected` -- добавил

2022-04-10 14:59 UTC, Handaz approved these changes

2022-04-10 15:04 UTC, merged