Feature/47
frontend-team-12/ya-practicum-game pull request #55
Opened 2022-04-18 21:28 UTC by Handaz

**Добавил react-redux и @reduxjs/toolkit, а также типы к ним** 

В данный момент стор выполняет обновляет свой стейт после логина и при заходе на страницу профиля для получения данных о пользователе. Для этого в качестве временного решения поставил заглушки для получения данных.

Thunk используется для получения информации о пользователе в стор

Reselect пока не нашел лучшего применения, чем делать селектор для никнеймы пользователя. Это может быть полезно, так как именно этот параметр будет часто использоваться: профиль, форум, страница треда и тд.

Для хранения экшнов и редьюсеров использовал схему, описанную [здесь](https://github.com/erikras/ducks-modular-redux), по рекомендациям из чеклиста. Если вкратце, то она предполагает разделение хранилища на модули. Насчет хранения селекторов там же есть сомнения, но, в принципе, выглядит удобно.

2022-04-19 22:16 UTC, vishenkov requested changes

2022-04-19 22:16 UTC, vishenkov commented on src/store/ducks/user.ts
> +};
этот способ легитимный, но не очень мне нравится)

Как вариант на обсудить: я бы предпочел завести отдельный сервис, который бы дергал напрямую store

> services/user.ts

```typescript
import authApi from '@api/AuthApi';

import axios from 'axios';
import { setLoading, setLoadingState, setUser } from '@store/slices/currentUser';
import { store } from '@store/store';

// тут бы еще BaseService, который принимает location
// а сам location инициализируется из хука useLoaction в корневом useEffect в App.tsx
export default class UserService {
  location: Location;
  constructor(location: Location) {
    this.location = location;
  }

  async getCurrentUser() {
    store.dispatch(setLoading());

    try {
      const userResponse = await authApi.getUser();

      store.dispatch(setUser(userResponse.data));
    } catch (error) {
      console.log(error);
      setLoadingState('error');

      // @todo: add notifications
      if (axios.isAxiosError(error)) {
        if (error.response) {
          // The request was made and the server responded with a status code
          // that falls out of the range of 2xx
          console.log(error.response.data);
          if ([401, 403].includes(error.response.status)) {
            this.location.assign('/login');
          }
        } else if (error.request) {
          console.log(error.request);
        } else {
          console.log('Error', error.message);
        }
      }
    }
  }
}

```

2022-04-19 22:16 UTC, vishenkov commented on src/store/ducks/user.ts
> +};
^ это все в комбо с примером из slice

а компонент подписывается через useSelector на `loadingState` и `user` и дергает `userService.getUser()`

2022-04-19 22:16 UTC, vishenkov commented on src/pages/Profile/Profile.tsx
> +import { getUser, selectUserNickname } from '@store/ducks/user';
от этих ошибок легко избавиться - надо в `eslintrc.json` добавить:
```json
....
 "simple-import-sort/imports": [
      "error",
      {
        "groups": [
          // Packages. `react` related packages come first.
          ["^react"],
          ["^@mui"],
          // api files
          ["^@api"],
          // redux store
          ["^@store"],      // <------------------------------------------------
          // Internal packages.
....
```

2022-04-19 22:16 UTC, vishenkov commented on src/store/ducks/user.ts
> +};
еще можно прокинуть `const dispatch = useDispatch()` по аналогии с `location` в UserService

2022-04-19 22:16 UTC, vishenkov commented on src/pages/Profile/Profile.tsx
> +import { getUser, selectUserNickname } from '@store/ducks/user';
и заодно и `@reduxjs...` поставить после mui, например

2022-04-19 22:16 UTC, vishenkov commented on src/pages/Profile/components/UserInfo/UserInfo.tsx
> +  const { user } = store.getState();
такое лучше напрямую в компонентах не делать, а использовать селектор, так как изменение стора не вызовет тут ререндер

2022-04-19 22:36 UTC, vishenkov commented on src/store/ducks/user.ts
> +}
из примера
```
user: action.payload,
loadingState: 'loaded'
```
так, конечно, лучше не делать -- можно потом будет добавить через [batch](https://react-redux.js.org/api/batch)

2022-04-20 06:50 UTC, Handaz commented on src/pages/Login/Login.tsx
> +import { getUser } from '@store/ducks/user';
Описал в комментари пул реквеста

2022-04-20 06:53 UTC, Handaz commented on src/pages/Profile/Profile.tsx
> +  const [nickname, setNickname] = useState('');
Согласен, это временное решение, просто наш линтер требовал для асинхронной функции любой finally, чтобы не висел промис и я решил туда пока пихнуть стейт. С реализованной задачей на проверку авторизации этот юзэффект вообще не нужен будет, как и стейт локальный

2022-04-20 06:53 UTC, Handaz commented on src/pages/Profile/Profile.tsx
> +  const getProfileInfo = useCallback(async () => {
Эта функция временная, описал в другом комментарии

2022-04-20 06:54 UTC, Handaz commented on src/store/index.ts
> +export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector;
такую схему предлагают в документации редакса и я больше склонен к ней, потому что эти хуки зависят напрямую от нашего стора

2022-04-20 06:56 UTC, Handaz commented on src/store/ducks/user.ts
> +}
про слайсы как-то упустил, воспользуюсь)

2022-04-20 07:03 UTC, Handaz commented on src/store/ducks/user.ts
> +};
схема мне нравится, но тогда thunk отпадает, который у нас должен быть по условию + в него все так же можно закинуть обработку ошибок и статусов (idle, loading, success, error и тд)

2022-04-20 07:04 UTC, Handaz commented on src/pages/Profile/components/UserInfo/UserInfo.tsx
> +  const { user } = store.getState();
понял, привычка с моба)

2022-04-20 08:41 UTC, mblxa commented on src/store/ducks/user.ts
> +}
В редюсерах используется либа immer она сама создает новый объект в конце экшена
1) Ничего возвращать не надо
2) Нужно менять только то свойство, которое изменилось

`setLoading: state => { state.loadingState = 'loading' },`

2022-04-20 08:45 UTC, mblxa commented on src/store/ducks/user.ts
> +export const selectUserNickname = createSelector(
Добавляйте тайпинг к селекторам, это полезно =)

2022-04-20 16:26 UTC, vishenkov commented on src/store/ducks/user.ts
> +}
> В редюсерах используется либа immer она сама создает новый объект в конце экшена

да, но не хотелось бы ослаблять правила линтера на запрет изменения объекта по ссылке

2022-04-20 16:26 UTC, vishenkov commented on src/store/ducks/user.ts
> +}
можно добавить кастомный конфиг eslint в папку с редюсерами, но кажется такое себе решение

2022-04-20 16:27 UTC, vishenkov commented on src/store/ducks/user.ts
> +};
там в задачах написано поставить, но никто не заставляет использовать 😂

2022-04-20 16:30 UTC, vishenkov commented on src/store/ducks/user.ts
> +};
если оставим с redux-thunk, то придется заниматься обработкой ошибок в самом компоненте (как и редиректами/валидацией) -- кмк, такое удобнее делать в сервисе

2022-04-20 16:36 UTC, Handaz commented on src/store/ducks/user.ts
> +};
а кто мешает в thunk обработку ошибки сделать-то?

2022-04-20 16:36 UTC, vishenkov commented on src/pages/Login/Login.tsx
> +import { getUser } from '@store/ducks/user';
ага, я прочитал, но все равно кажется странным название)

2022-04-20 16:36 UTC, Handaz commented on src/store/ducks/user.ts
> +};
по сути, то же самое будет практически, только через функцию, а не через класс

2022-04-20 16:40 UTC, Handaz commented on src/store/ducks/user.ts
> +}
> > В редюсерах используется либа immer она сама создает новый объект в конце экшена
> 
> да, но не хотелось бы ослаблять правила линтера на запрет изменения объекта по ссылке

я отключил это правило в ходе правок по пулу, так как оно в случае работы с immer и redux действительно бессмысленно

2022-04-20 16:46 UTC, vishenkov commented on src/store/ducks/user.ts
> +};
location из react-router-dom туда просто так не прокинуть - то есть, придется в компоненте их обрабатывать

2022-04-20 16:58 UTC, Handaz commented on src/store/ducks/user.ts
> +};
можно же параметром в функцию это отправить, thunk их способен принимать

2022-04-20 20:48 UTC, Handaz commented on src/store/ducks/user.ts
> +};
я передачу параметром предложил в качестве альтернативы через инициализации через конструктор, а так, можно другие способы использовать

2022-04-22 10:17 UTC, Evgood approved these changes

2022-04-22 21:33 UTC, vishenkov requested changes

2022-04-22 21:33 UTC, vishenkov commented on src/pages/Profile/components/UserInfo/UserInfo.tsx
> +import { selectUserData } from '@store/slices/user';
все же, кмк, намного удобнее будет вынести все селекторы в один файл, так как потом будет неудобно искать в каком именно файле он был объявлен

2022-04-23 20:02 UTC, vishenkov commented on src/pages/Profile/components/UserLinks/UserLinks.tsx
> +    await authApi.logout();
можно добавить `@todo` -- очищать юзера в стейте

2022-04-25 23:02 UTC, vishenkov approved these changes

2022-04-26 07:34 UTC, merged