Feature/45: Auth check
frontend-team-12/ya-practicum-game pull request #57
Opened 2022-04-20 21:06 UTC by vishenkov

Проверяем авторизацию для роутов

2022-04-20 21:24 UTC, Handaz requested changes

2022-04-20 21:24 UTC, Handaz commented on src/Routes/Routes.tsx
> +      <Route path={RoutesMap.root} element={<Home />} />
Имеет смысл тогда Home и Leaderboard кинуть в авторизованные пути

2022-04-21 20:23 UTC, vishenkov commented on src/Routes/Routes.tsx
> +      <Route path={RoutesMap.root} element={<Home />} />
> Home
по идее, Home это точка входа, где сейчас описание -- поэтому должна быть доступна всем

по клику на Play перекидывает на авторизацию

> Leaderboard
Тут тоже спорно -- по идее, часто в играх таблицу лидеров показывают всем

2022-04-21 21:07 UTC, Handaz commented on src/Routes/Routes.tsx
> +      <Route path={RoutesMap.root} element={<Home />} />
мне кажется логичнее кидать неавторизованных пользователей всегда на логин/регистрацию, как это делают в социальных сетях, к примеру

2022-04-22 10:08 UTC, Evgood approved these changes

2022-04-22 20:25 UTC, vishenkov commented on src/Routes/Routes.tsx
> +      <Route path={RoutesMap.root} element={<Home />} />
Большинство соц сетей позволяют смотреть контент без авторизации. Здесь такая же логика - показываем куда человек попал, а потом просим авторизоваться, если хочет играть

2022-04-23 19:38 UTC, Handaz approved these changes

2022-04-23 20:01 UTC, merged